{
 "title": "Dashboard terraform",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(jvm_info,job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{job=\"$service\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Количество созданных заказов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(orders_create_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (area, id) (jvm_memory_used_bytes{job=~\"$service\", instance=~\"$instance\", area=~\"heap|nonheap\"} / 1024 / 1024)",
     "legendFormat": "{{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "Live threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_threads_live_threads{job=~\"${service}\", instance=~\"${instance}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 latency $service : $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri, method) (rate(http_server_requests_seconds_bucket{job=~\"$service\", instance=~\"$instance\"}[5m]))) * 1000",
     "legendFormat": "{{method}} : {{uri}}"
    }
   ]
  },
  {
   "title": "Average latency $service : $instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_sum{job=~\"$service\", instance=~\"$instance\"}[5m])) / sum by (uri, method) (rate(http_server_requests_seconds_count{job=~\"$service\", instance=~\"$instance\"}[5m])) * 1000",
     "legendFormat": "{{method}} : {{uri}}"
    }
   ]
  },
  {
   "title": "500 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"${service}\", instance=~\"${instance}\", status=~\"5..\"}[1m]))",
     "legendFormat": "500 Errros - ${service} - ${instance}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=~\"${service}\", instance=~\"${instance}\"}[5m]))",
     "legendFormat": "RPS - ${service} - ${instance}"
    }
   ]
  }
 ]
}